title: Mike Freeman - Talking About Freedom
description: > # this means to ignore newlines until "baseurl:"
  How do you suck on the maorrow of life? For me it's about delivering massive value doing something I find hugely rewarding and at the same time quite effortless.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://mikefreeman.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Mike Freeman # add your name
author-img: mike-freeman-cartoon.png # add your photo
about-author: Husband | Happiness guy | Speaker | Investor | Entrepreneur | Educator | Troubleshooter | Techie | Crypto enthusiast # add description
twitter: _MikeFreeman # add your Twitter handle
facebook: mikefreemanonline # add your Facebook handle
github: mikefreeman-uk # add your Github handle
linkedin: mikefreemanonline # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
